### PR TITLE
Fixed end-of-life runtime error.

### PR DESCRIPTION
**Pull request by guylamar2006**

### CODE REVIEW

**Review by PhilipK — APPROVED** [review]

**Comment by PhilipK** [comment]
Thanks for doing this!
It seems the build is failing as the linter gets mad about some of the finish-arguments permissions. 

From what I can read, we can get around that by making a new file in the repo:
.flatpak-builder/lint-ignore.json

With the following content:

{
  "ignored-issues": [
    "finish-args-unnecessary-xdg-data-flatpak-ro-access",
    "finish-args-unnecessary-xdg-data-lutris-ro-access",
    "finish-args-unnecessary-xdg-data-Steam-rw-access"
  ]
}

**Comment by PhilipK** [comment]
> Thanks for doing this! It seems the build is failing as the linter gets mad about some of the finish-arguments permissions.
> 
> From what I can read, we can get around that by making a new file in the repo: .flatpak-builder/lint-ignore.json
> 
> With the following content:
> 
> { "ignored-issues": [ "finish-args-unnecessary-xdg-data-flatpak-ro-access", "finish-args-unnecessary-xdg-data-lutris-ro-access", "finish-args-unnecessary-xdg-data-Steam-rw-access" ] }

Well turns out no, exceptions are granted on a case by case basis: https://docs.flathub.org/docs/for-app-authors/linter#exceptions

Problem is, this app really does need these permissions, but I understand why they by default think it is a bad idea.

**Comment by PhilipK** [comment]
I made a pull request for exceptions here:
https://github.com/flathub-infra/flatpak-builder-lint/pull/516

**Comment by guylamar2006** [comment]
@PhilipK 

error[E0282]: type annotations needed for `Box<_>`
  --> /run/build/boilr/cargo/vendor/time-0.3.21/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

**Comment by PhilipK** [comment]
> @PhilipK
> 
> error[E0282]: type annotations needed for `Box<_>` --> /run/build/boilr/cargo/vendor/time-0.3.21/src/format_description/parse/mod.rs:83:9 | 83 | let items = format_items | ^^^^^ ... 86 | Ok(items.into()) | ---- type must be known at this point | = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

On it:
https://github.com/PhilipK/BoilR/pull/415

**Comment by PhilipK** [comment]
@guylamar2006 alright, new version of BoilR with all dependencies updated. This means that the commit hash needs to be updated and since there are new dependencies the cargo-lock file also needs updated.
The hash needs updated here: https://github.com/flathub/io.github.philipk.boilr/blob/467dd4b4e8131e77f70730b9dad0eea7e1d4f024/io.github.philipk.boilr.yml#L45

The new hash is the newest commit on the BoilR repo, this is it: 10caa7bee196922cc3f9df1354cc3516b89fa515
The updated cargo-lock file can be found here: https://raw.githubusercontent.com/PhilipK/BoilR/refs/heads/main/flatpak/cargo-lock.json
Just copy paste it into this PR.

Let me know if you need help with it.

**Comment by guylamar2006** [comment]
@PhilipK I sent the new commit id hash and cargo-lock.json both as commits.

**Comment by PhilipK** [comment]
@guylamar2006 Cool, i will merge as soon as the build is done.

**Comment by guylamar2006** [comment]
@PhilipK buildbot never triggered when I sent the new commits.

**Comment by PhilipK** [comment]
@guylamar2006 I can see that the build is still pending, so just wait it out, some times it takes a long time.

**Comment by PhilipK** [comment]
@guylamar2006 don't you can see this but: https://buildbot.flathub.org/#/buildrequests/632803

**Review by PhilipK — APPROVED** [review]

**Pull request merged**
